FROM node
FROM ghcr.io/puppeteer/puppeteer:22.3.0

WORKDIR /usr/src/scrap
RUN chown -Rh $user:$user /usr/src/scrap
USER $user

COPY . .

RUN npm install 
RUN npm install @types/cheerio
RUN npm run build

CMD ["npm", "run", "start:prod"]