FROM node
FROM ghcr.io/puppeteer/puppeteer:22.3.0


ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable


WORKDIR /usr/src/scrap


COPY . .

RUN npm install 
RUN npm install @types/cheerio
RUN npm run build

CMD ["npm", "run", "start:prod"]